[package]
name = "engine_store_ffi"
version = "0.0.1"
authors = ["The TiKV Authors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
default = ["test-engine-kv-rocksdb", "test-engine-raft-raft-engine"]
failpoints = ["fail/failpoints"]
testexport = []
test-engine-kv-rocksdb = [
  "engine_test/test-engine-kv-rocksdb"
]
test-engine-raft-raft-engine = [
  "engine_test/test-engine-raft-raft-engine"
]
test-engines-rocksdb = [
  "engine_test/test-engines-rocksdb",
]
test-engines-panic = [
  "engine_test/test-engines-panic",
]
enable-pagestorage = []

cloud-aws = ["sst_importer/cloud-aws"]
cloud-gcp = ["sst_importer/cloud-gcp"]
cloud-azure = ["sst_importer/cloud-azure"]

[dependencies]
batch-system = { workspace = true, default-features = false }
bitflags = "1.0.1"
byteorder = "1.2"
bytes = "1.0"
collections = { workspace = true }
crossbeam = "0.8"
derivative = "2"
encryption = { workspace = true, default-features = false }
engine_rocks = { workspace = true, default-features = false }
# Should be [dev-dependencies] but we need to control the features
# https://github.com/rust-lang/cargo/issues/6915
engine_test = { workspace = true, default-features = false }
engine_tiflash = { workspace = true, default-features = false }
engine_traits = { workspace = true, default-features = false }
error_code = { workspace = true, default-features = false }
fail = "0.5"
file_system = { workspace = true, default-features = false }
fs2 = "0.4"
futures = "0.3"
futures-util = { version = "0.3.1", default-features = false, features = ["io"] }
getset = "0.1"
grpcio-health = { version = "0.10", default-features = false, features = ["protobuf-codec"] }
into_other = { workspace = true, default-features = false }
itertools = "0.10"
keys = { workspace = true, default-features = false }
kvproto = { git = "https://github.com/pingcap/kvproto.git" }
lazy_static = "1.3"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
log_wrappers = { workspace = true }
online_config = { workspace = true }
ordered-float = "2.6"
parking_lot = "0.12"
pd_client = { workspace = true, default-features = false }
portable-atomic = "0.3"
prometheus = { version = "0.13", features = ["nightly"] }
prometheus-static-metric = "0.5"
protobuf = { version = "2.8", features = ["bytes"] }
proxy_ffi = { workspace = true, default-features = false }
raft = { version = "0.7.0", default-features = false, features = ["protobuf-codec"] }
raft-proto = { version = "0.7.0", default-features = false }
raftstore = { workspace = true, default-features = false }
rand = "0.8.3"
serde = "1.0"
serde_derive = "1.0"
serde_with = "1.4"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
smallvec = "1.4"
sst_importer = { workspace = true, default-features = false }
tempfile = "3.0"
thiserror = "1.0"
tikv_alloc = { workspace = true }
tikv_util = { workspace = true, default-features = false }
time = "0.1"
tokio = { version = "1.5", features = ["sync", "rt-multi-thread"] }
tokio-timer = { git = "https://github.com/tikv/tokio", branch = "tokio-timer-hotfix" }
tracker = { workspace = true, default-features = false }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
yatp = { git = "https://github.com/tikv/yatp.git", branch = "master" }

[dev-dependencies]
encryption_export = { workspace = true, default-features = false }
engine_panic = { workspace = true, default-features = false }
panic_hook = { workspace = true }
test_sst_importer = { workspace = true, default-features = false }
